services:
  web:
    build: .
    expose:
      - "5000"
    environment:
      - FLASK_APP=app.main:app
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - PYTHONPATH=/code:/code/app
    volumes:
      - ./data:/code/data
    command: ["flask", "run"]

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/code/app/static:ro
    restart: unless-stopped
